version: 2

jobs:
  build:
    docker:
      - image: mobify/cci-docker-primary:0.0.15
    workDir: /home/ubuntu/platform-scaffold/
    steps:
      - checkout
      - restore_cache:
          key: platform-scaffold-{{ .Branch }}-{{ checksum "web/package.json" }}
          paths:
            - /home/ubuntu/platform-scaffold/web/node_modules
      - run:
          name: Install Dependencies
          command: cd web && npm install
      - save_cache:
          key: platform-scaffold-{{ .Branch }}-{{ checksum "web/package.json" }}
          paths:
            - /home/ubuntu/platform-scaffold/web/node_modules
      - run:
          name: Lint
          command: cd web && npm run lint     
      - persist_to_workspace:
          root: .
          paths: .

  test-server:
    docker:
      - image: mobify/cci-docker-primary:0.0.15
    workDir: /home/ubuntu/platform-scaffold/
    steps:
      - attach_workspace:
          at: /home/ubuntu/platform-scaffold/
      - run:
          name: Start Test Server
          command: bash ./web/tests/system/test-scripts/start-test-server.sh
          background: true
      - run:
          name: Wait for Server
          command: bash ./web/scripts/wait-for-dependencies.sh

  test-e2e:
    docker:
      - image: mobify/cci-docker-primary:0.0.15
    workDir: /home/ubuntu/platform-scaffold/
    steps:
      - attach_workspace:
          at: /home/ubuntu/platform-scaffold/
      - run: 
          name: Run end2end Test
          command: cd web && xvfb-run -a npm run test:e2e
          when: always
      - store_artifacts:
          path: web/tests/reports/
          when: always
      - store_artifacts:
          path: web/tests/screenshots/system/workflows/
          when: always
      
  test-performance:
    docker:
      - image: mobify/cci-docker-primary:0.0.15
    workDir: /home/ubuntu/platform-scaffold/
    steps:
      - attach_workspace:
          at: /home/ubuntu/platform-scaffold/
      - run:
          name: Lighthouse Tests
          command: cd web && xvfb-run -a npm run test:pwa-preview
          when: always
      - store_artifacts:
          path: web/tests/system/test-scripts/lighthouse/reports/
          when: always

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test-server:
          requires:
            - build
      - test-e2e:
          requires:
            - build
      - test-performance:
          requires:
            - build