version: 2

jobs:
  build:
    docker:
      - image: mobify/cci-docker-primary:0.0.15
    workDir: /home/ubuntu/platform-scaffold/
    steps:
      - checkout
      - restore_cache:
          key: platform-scaffold-{{ .Branch }}-{{ checksum "web/package.json" }}
          paths:
            - /home/ubuntu/platform-scaffold/web/node_modules
      - run: cd web
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: platform-scaffold-{{ .Branch }}-{{ checksum "web/package.json" }}
          paths:
            - /home/ubuntu/platform-scaffold/web/node_modules
      - run:
          name: Accept Cert
          command: bash ./scripts/accept-cert-ci.sh
      - run:
          name: Lint
          command: npm run lint     
      - persist_to_workspace:
          root: .
          paths: .

  run-all-tests:
    docker:
      - image: mobify/cci-docker-primary:0.0.15
    workDir: /home/ubuntu/platform-scaffold/
    parallelism: 3
    resource_class: large
    steps:
      - attach_workspace:
          at: /home/ubuntu/platform-scaffold/
      - run: cd web
      - run:
          name: Start Test Server
          command: bash ./tests/system/test-scripts/start-test-server.sh
          background: true
      - run:
          name: Wait for Server
          command: bash ./scripts/wait-for-dependencies.sh
      - run:
          name: Run-All-Tests
          command: bash ./tests/system/test-scripts/run-all-tests-on-ci.sh
  
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - run-all-tests:
          requires:
            - build